# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'r_hapi'
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ['Tim Stephenson of RaddOnline']
  s.date = '2011-09-22'
  s.description = 'Makes it easy to use the HubSpot API in a Ruby application.'
  s.email = 'tim@raddonline.com'
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/r_hapi.rb",
    "lib/r_hapi/configuration.rb",
    "lib/r_hapi/connection.rb",
    "lib/r_hapi/lead.rb",
    "lib/r_hapi/r_hapi_exception.rb",
    "r_hapi.gemspec",
    "spec/config.yml.sample",
    "spec/configuration_spec.rb",
    "spec/fixtures/error.html",
    "spec/fixtures/lead.json",
    "spec/fixtures/leads.json",
    "spec/lead_spec.rb",
    "spec/r_hapi_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = 'http://github.com/timstephenson/rHAPI'
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = '1.8.6'
  s.summary = 'A ruby wrapper for the HubSpot API (HAPI).'
  s.test_files = [
    "spec/configuration_spec.rb",
    "spec/lead_spec.rb",
    "spec/r_hapi_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency('curb')
      s.add_runtime_dependency('json')
      s.add_runtime_dependency('activesupport')
      s.add_runtime_dependency('nokogiri')
      s.add_development_dependency('rspec')
      s.add_development_dependency('bundler')
      s.add_development_dependency('jeweler')
    else
      s.add_dependency('curb')
      s.add_dependency('json')
      s.add_dependency('activesupport')
      s.add_dependency('nokogiri')
      s.add_dependency('rspec')
      s.add_dependency('bundler')
      s.add_dependency('jeweler')
    end
  else
    s.add_dependency('curb')
    s.add_dependency('json')
    s.add_dependency('activesupport')
    s.add_dependency('nokogiri')
    s.add_dependency('rspec')
    s.add_dependency('bundler')
    s.add_dependency('jeweler')
  end
end
